#!/usr/bin/env bash
# ============================================================
# INFERNIS Local Development Setup
# ============================================================
# Prerequisites: macOS with Homebrew, Python 3.11+
#
# This script:
#   1. Installs & starts PostgreSQL 17 + PostGIS 3.6
#   2. Installs & starts Redis
#   3. Creates the infernis database with PostGIS
#   4. Creates a Python venv and installs dependencies
#   5. Runs Alembic migrations
#   6. Runs the full test suite
#   7. Runs the E2E test (pipeline + API validation)
#
# Usage:
#   chmod +x scripts/dev_setup.sh
#   ./scripts/dev_setup.sh
# ============================================================

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[FAIL]${NC} $*"; }

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJECT_ROOT"

# ── Step 1: PostgreSQL ──────────────────────────────────────────────
info "Checking PostgreSQL..."
if ! command -v pg_isready &>/dev/null; then
    info "Installing PostgreSQL 17 via Homebrew..."
    brew install postgresql@17
fi

if ! pg_isready -q 2>/dev/null; then
    info "Starting PostgreSQL..."
    brew services start postgresql@17 || brew services start postgresql
    sleep 2
fi

if pg_isready -q; then
    info "PostgreSQL is running"
else
    error "PostgreSQL failed to start"
    exit 1
fi

# Create database if it doesn't exist
DB_NAME="infernis"
if psql -lqt | cut -d \| -f 1 | grep -qw "$DB_NAME"; then
    info "Database '$DB_NAME' already exists"
else
    info "Creating database '$DB_NAME'..."
    createdb "$DB_NAME"
fi

# Enable PostGIS
info "Ensuring PostGIS extension..."
if ! brew list postgis &>/dev/null; then
    info "Installing PostGIS..."
    brew install postgis
fi
psql -d "$DB_NAME" -c "CREATE EXTENSION IF NOT EXISTS postgis;" 2>/dev/null
info "PostGIS enabled"

# ── Step 2: Redis ───────────────────────────────────────────────────
info "Checking Redis..."
if ! command -v redis-server &>/dev/null; then
    info "Installing Redis via Homebrew..."
    brew install redis
fi

if ! redis-cli ping &>/dev/null 2>&1; then
    info "Starting Redis..."
    brew services start redis
    sleep 1
fi

if redis-cli ping 2>/dev/null | grep -q PONG; then
    info "Redis is running"
else
    error "Redis failed to start"
    exit 1
fi

# ── Step 3: Python venv ────────────────────────────────────────────
info "Checking Python virtual environment..."
if [ ! -d ".venv" ]; then
    info "Creating venv..."
    python3 -m venv .venv
fi

PYTHON=".venv/bin/python"
PIP=".venv/bin/pip"

info "Installing Python dependencies..."
$PIP install -q -e ".[dev]" 2>&1 | tail -1

# ── Step 4: .env configuration ──────────────────────────────────────
if [ ! -f ".env" ]; then
    info "Creating .env from .env.example..."
    cp .env.example .env
    # Set local dev defaults
    DB_USER=$(whoami)
    cat > .env.local <<EOF
# Local dev overrides (auto-generated by dev_setup.sh)
INFERNIS_DEBUG=true
INFERNIS_DATABASE_URL=postgresql://${DB_USER}@localhost:5432/infernis
INFERNIS_REDIS_URL=redis://localhost:6379/0
INFERNIS_GRID_PARQUET_PATH=data/processed/grid_1km.parquet
INFERNIS_GRID_RESOLUTION_KM=1.0
INFERNIS_FORECAST_ENABLED=true
EOF
    cat .env.local >> .env
    rm .env.local
    warn "Created .env — edit it to add API keys (CDS, GEE, NASA, Firebase)"
else
    info ".env already exists"
fi

# ── Step 5: Alembic migrations ──────────────────────────────────────
info "Running database migrations..."
DB_USER=$(whoami)

# alembic/env.py reads INFERNIS_DATABASE_URL from environment
INFERNIS_DATABASE_URL="postgresql://${DB_USER}@localhost:5432/infernis" \
    $PYTHON -m alembic upgrade head
info "Migrations complete"

# ── Step 6: Verify data files ───────────────────────────────────────
info "Checking data files..."
GRID_FILE="data/processed/grid_1km.parquet"
MODEL_FILE="models/fire_core_1km_v1.json"

if [ -f "$GRID_FILE" ]; then
    info "Grid parquet found: $GRID_FILE"
else
    warn "Grid parquet missing: $GRID_FILE"
    warn "Run: python scripts/generate_grid.py --resolution 1 to generate it"
fi

if [ -f "$MODEL_FILE" ]; then
    info "XGBoost model found: $MODEL_FILE"
else
    warn "XGBoost model missing: $MODEL_FILE"
    warn "Run: python scripts/retrain_1km.py to train it"
fi

# ── Step 7: Run tests ──────────────────────────────────────────────
info "Running test suite..."
if $PYTHON -m pytest tests/ --ignore=tests/test_heatmap.py -x -q 2>&1; then
    info "All tests passed"
else
    error "Some tests failed — check output above"
    exit 1
fi

# Heatmap tests (PyTorch, may be slow on first run)
info "Running heatmap tests..."
if $PYTHON -m pytest tests/test_heatmap.py -x -q 2>&1; then
    info "Heatmap tests passed"
else
    warn "Heatmap tests failed (PyTorch may need a warm-up run)"
fi

# ── Step 8: E2E test ───────────────────────────────────────────────
info "Running end-to-end test..."
if $PYTHON scripts/e2e_test.py 2>&1; then
    info "E2E test passed"
else
    error "E2E test failed — check output above"
    exit 1
fi

# ── Done ────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  INFERNIS local dev environment ready  ${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "Start the API server:"
echo "  .venv/bin/uvicorn infernis.main:app --reload"
echo ""
echo "Run tests:"
echo "  .venv/bin/python -m pytest tests/ -q"
echo ""
echo "Run E2E test:"
echo "  .venv/bin/python scripts/e2e_test.py"
echo ""
